maps/boost_nuke.res
maps/boost_nuke.txt
gfx/env/wbskybk.tga
gfx/env/wbskydn.tga
gfx/env/wbskyft.tga
gfx/env/wbskylf.tga
gfx/env/wbskyrt.tga
gfx/env/wbskyup.tga
models/pi_tree.mdl
models/forge_tree1.mdl
models/dnc_truck1.mdl
models/dnc_pipe1.mdl
models/dnc_fence1.mdl
models/dnc_fan1.mdl
models/dnc_fan2.mdl
models/dnc_bigbar1.mdl
models/dnc_bigbar2.mdl
models/bush_japan_fern_01.mdl
sounds/birds_sound01.wav