maps/boost_cbble.res
gfx/env/nature01bk.tga
gfx/env/nature01dn.tga
gfx/env/nature01ft.tga
gfx/env/nature01lf.tga
gfx/env/nature01rt.tga
gfx/env/nature01up.tga
models/bush14.mdl
models/bush_japan_fern_01.mdl
models/flower.mdl
models/forge_tree1.mdl
sprites/boost_cbble/watersmoke.spr
sound/windyforest.wav
sound/halla_water1.wav