gfx/env/trainyardup.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardft.tga
gfx/env/trainyardbk.tga
models/pi_tree.mdl
sprites/laserbeam.spr
sound/hnsru_ft/hnsru1.wav
sound/hnsru_ft/hnsru2.wav
sound/hnsru_ft/hnsru3.wav
sound/hnsru_ft/hnsru4.wav
sound/hnsru_ft/hnsru5.wav
sound/hnsru_ft/hnsru6.wav
sound/hnsru_ft/hnsru8.wav
sound/hnsru_ft/hnsru9.wav
sound/hnsru_ft/hnsru10.wav
sound/hnsru_ft/hnsru11.wav
sound/hnsru_ft/hnsru12.wav
sound/hnsru_ft/hnsru13.wav
sound/hnsru_ft/hnsru14.wav
sound/hnsru_ft/hnsru15.wav
sound/hnsru_ft/hnsru16.wav
sound/hnsru_ft/hnsru7.wav
sound/hnsru_ft/hnsru17.wav
sound/hnsru_ft/hnsru18.wav
sound/hnsru_ft/hnsru19.wav
sound/hnsru_ft/hnsru20.wav
sound/hnsru_ft/hnsru21.wav
sound/hnsru_ft/hnsru22.wav
sound/hnsru_ft/hnsru23.wav
sound/hnsru_ft/hnsru24.wav
sound/hnsru_ft/hnsru25.wav
sound/hnsru_ft/hnsru26.wav
sound/hnsru_ft/hnsru27.wav
sound/hnsru_ft/hnsru28.wav
sound/hnsru_ft/hnsru29.wav
