gfx/env/desert_evening_bk.tga
gfx/env/desert_evening_dn.tga
gfx/env/desert_evening_ft.tga
gfx/env/desert_evening_lf.tga
gfx/env/desert_evening_rt.tga
gfx/env/desert_evening_up.tga
overviews/rayish_ruins.tga
overviews/rayish_ruins.txt
maps/rayish_ruins.txt
maps/rayish_ruins.res