//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/rg_world.html
cs_cbble.wad
cstrike.wad
timecounter.wad
liquids.wad
gfx/env/drkgbk.tga
gfx/env/drkgdn.tga
gfx/env/drkgft.tga
gfx/env/drkglf.tga
gfx/env/drkgrt.tga
gfx/env/drkgup.tga
sprites/flamelight.spr
maps/rg_world.bsp
